name: FastCrystals
version: 1.0
api-version: 1.20
main: xyz.exyron.fastcrystals.FastCrystalsPlugin
authors: [ Exyron.XYZ, KamlaX, KinczeK ]
depend: [ ProtocolLib ]
softdepend: [ PlaceholderAPI ]
commands:
  fastcrystals:
    aliases: [ fastercrystals, fastcrystal, quickcrystal ]